# Generated by Django 5.0 on 2023-12-22 10:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_rename_board_boards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('checked', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('high', 'high')], default='Low', max_length=20)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Awaiting Feedback', 'Awaiting Feedback'), ('done', 'done')], default='Todo', max_length=20)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
