# Generated by Django 5.0 on 2023-12-22 11:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_tickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Awaiting Feedback', 'Awaiting Feedback'), ('Done', 'Done')], default='Todo', max_length=20),
        ),
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('checked', models.BooleanField(default=False)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('assigned', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='subtasks',
            field=models.ManyToManyField(related_name='subtasks', to='workspace.subtasks'),
        ),
    ]
