# Generated by Django 5.0 on 2023-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_tickets_assigned_to_alter_tickets_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='tickets',
            field=models.ManyToManyField(related_name='tickets', to='workspace.tickets'),
        ),
    ]
