# Generated by Django 5.0 on 2023-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_boards_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='subtasks',
            field=models.ManyToManyField(default=None, related_name='subtasks', to='workspace.subtasks'),
        ),
    ]
