# Generated by Django 5.0 on 2023-12-22 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_alter_subtasks_creator_alter_subtasks_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boards',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='Subtasks',
            new_name='Subtask',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
