# Generated by Django 5.0 on 2023-12-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_rename_boards_board_rename_subtasks_subtask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='workspace.ticket'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='subtasks', to='workspace.subtask'),
        ),
    ]
